services:
  esp32-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    image: esp32-dev:latest
    container_name: esp32-dev
    volumes:
      - ./project:/project
      - esp32-build-cache:/root/.espressif
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0  # Adjust based on your USB port
    privileged: true
    working_dir: /project
    stdin_open: true
    tty: true
    command: /bin/bash

volumes:
  esp32-build-cache:
